{
 "title": "Tessara Consumer Metrics",
 "tags": [
  "go",
  "prometheus",
  "kafka",
  "example"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Memory Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Buffer Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_buffer_size" }
   ]
  },
  {
   "title": "Total Uncommitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "${A} - ${C}", "type": "math" }
   ]
  },
  {
   "title": "Buffer Pushed Messages, Current Water Mark",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 6, "y": 1 },
   "targets": [
    { "expr": "current_buffer", "legendFormat": "__auto" },
    { "expr": "current_watermark", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Push Buffer Wating Time (seconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "push_to_buffer_waiting_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Pushed Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_buffer", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Water Mark",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_watermark", "legendFormat": "__auto" }
   ]
  },
  { "title": "Subqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Subqueue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subqueue_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processing Messages",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 7, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subqueue_message_processing_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 7, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subqueue_message_processed_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retried Messages",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subqueue_message_error_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Subqueue Channel Buffer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subqueue_channel_buffer_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Processing Time (seconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "subqueue_message_processing_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}