services:
  consumer1:
    build:
      context: .
    container_name: consumer1
    volumes:
      - ../../../:/src/go
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /src/go/_example/consumer/testrun
    command: air -c .air.toml
    env_file:
      - .env
    ports:
      - '2112:2112'
    depends_on:
      - kafka
      - prometheus
      - grafana
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: 'SCRAM-SHA-512'
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="kafkaUser" password="kafkaPassword";'
      KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL: 'SASL'
      DYNAMIC_CONFIG_ENABLED: 'true'
    logging:
      driver: none

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    command: >
      bash -c "kafka-configs.sh --zookeeper zookeeper:2181 --alter --add-config='SCRAM-SHA-512=[password=kafkaPassword]' --entity-type users --entity-name kafkaUser && start-kafka.sh"
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf'
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:SASL_PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512
      KAFKA_CREATE_TOPICS: 'example-topic:2:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./producer.properties:/opt/kafka/config/producer.properties
    links:
      - zookeeper

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../../../script/metric/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - kafka
      - zookeeper

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ../../../script/metric/grafana:/etc/grafana/provisioning
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
